services:
  dominion:
    build: 
      context: ./dominion
      dockerfile: Containerfile
    ports:
      - "5173:5173"
    networks:
      - dominion
    volumes:
      - ./dominion:/app:z
      - /app/node_modules
    user: root
    environment:
      - HOST=0.0.0.0
    command: pnpm dev

  dominion-api:
    build:
      context: ./dominion-api
      dockerfile: Containerfile
    ports:
      - "3000:3000"
    networks:
      - dominion
    volumes:
      - ./dominion-api:/app:z
    environment:
      - PORT=3000
    command: air -c .air.toml

  dev:
    build: .
    networks:
      - dominion
    volumes:
      - ./dominion-api:/dominion-api:z
      - ./dominion:/dominion:z
      - /app/node_modules
    command: sleep infinity

networks:
  dominion:
    driver: bridge