services:
  dominion:
    build: 
      context: ./dominion
      dockerfile: Containerfile
    ports:
      - "5173:5173"
    volumes:
      - ./dominion:/app:z
    user: root
    environment:
      - HOST=0.0.0.0
    command: pnpm dev

  dominion-api:
    build:
      context: ./dominion-api
      dockerfile: Containerfile
    ports:
      - "3000:3000"
    volumes:
      - ./dominion-api:/app:z
    environment:
      - PORT=3000
    command: air -c .air.toml
