[vite-builder]
additional_packages="nodejs24 npm24 git curl gawk"
image=registry.opensuse.org/opensuse/distrobox:latest
root=false
# Install pnpm
init_hooks=npm install -g pnpm@latest-10;
# Install Node Packages in /node_modules/
init_hooks=cd /home/tie/dominion/dominion && pnpm install && cd /home/tie/dominion;
# Install Go
init_hooks=[ ! -f go.tar.gz ] && curl -o go.tar.gz https://dl.google.com/go/go1.26.1.linux-amd64.tar.gz;
init_hooks=rm -rf /usr/local/go && tar -C /usr/local -xzf go.tar.gz;
init_hooks=echo 'export PATH=/usr/local/go/bin:$PATH' > /etc/profile.d/go.sh;
init_hooks=source /etc/profile.d/go.sh;
# Install Go dependencies
init_hooks=cd /home/tie/dominion/dominion-api && go mod download && cd /home/tie/dominion;
# Join compose network
additional_flags="--network dominion"