[vite-builder]
additional_packages="nodejs24 npm24 git curl gawk"
image=registry.opensuse.org/opensuse/distrobox:latest
# Install pnpm
init_hooks=npm install -g pnpm@latest-10;
# Install Go
init_hooks=curl -o go.tar.gz https://dl.google.com/go/go1.26.1.linux-amd64.tar.gz;
init_hooks=rm -rf /usr/local/go && tar -C /usr/local -xzf go.tar.gz;