[vite-builder]
additional_packages="curl gawk git make nodejs24 npm24"
image=registry.opensuse.org/opensuse/tumbleweed:latest
root=false
init=true
# Install pnpm
init_hooks=npm install -g pnpm@latest-10;
# Install Node Packages in /node_modules/
init_hooks=cd /home/tie/dominion/dominion && pnpm install && cd /home/tie/dominion;
# Install Go
init_hooks=[ ! -f go.tar.gz ] && curl -o go.tar.gz https://dl.google.com/go/go1.26.1.linux-amd64.tar.gz;
init_hooks=rm -rf /usr/local/go && tar -C /usr/local -xzf go.tar.gz;
init_hooks=echo 'export PATH=/usr/local/go/bin:/home/tie/go/bin:$PATH' > /etc/profile.d/go.sh;
init_hooks=source /etc/profile.d/go.sh;
# Install air for hot-reloading
init_hooks=go install github.com/air-verse/air@latest;
# Install Go dependencies
init_hooks=cd /home/tie/dominion/dominion-api && go mod download && cd /home/tie/dominion;
